INSERT INTO quizzes (id, title, author, questions, answers, options)
VALUES 
  ("cg2541", "Science Quiz", "Chris", '["What is the smallest element in the periodic table?", "What is the largest planet in the solar system?", "What is the boiling point of water?", "What is the fastest animal on land?"]', '["Hydrogen", "Jupiter", "100 degrees Celsius", "Cheetah"]', '[["Oxygen", "Helium", "Carbon"], ["Neptune", "Saturn", "Mars"], ["50 degrees Celsius", "150 degrees Celsius", "200 degrees Celsius"], ["Gazelle", "Lion", "Leopard"]]'),
  ("bm8329", "Movie Quiz", "Bob", '["What is the highest-grossing movie of all time?", "Who played Neo in the Matrix trilogy?", "Who directed The Godfather?", "Who played the character of Harry Potter in the Harry Potter series?"]', '["Avatar", "Keanu Reeves", "Francis Ford Coppola", "Daniel Radcliffe"]', '[["Titanic", "Avengers: Endgame", "Star Wars: The Force Awakens"], ["Hugo Weaving", "Laurence Fishburne", "Brad Pitt"], ["Steven Spielberg", "Martin Scorsese", "Quentin Tarantino"], ["Rupert Grint", "Tom Felton", "Emma Watson"]]'),
  ("al4597", "Geography Quiz", "Alice", '["Which river is the longest in the world?", "What is the capital of France?", "Which country is both the smallest by land area and population?", "What is the highest mountain peak in Africa?"]', '["Nile", "Paris", "Vatican City", "Mount Kilimanjaro"]', '[["Amazon", "Mississippi", "Yangtze"], ["Madrid", "Rome", "Berlin"], ["Monaco", "Nauru", "Liechtenstein"], ["Mount Everest", "Mount Kenya", "Mount Meru"]]'),
  ("sd1620", "Literature Quiz", "Sarah", '["What is the name of the protagonist in The Catcher in the Rye?", "Who wrote The Great Gatsby?", "What is the name of the fictional land in The Lord of the Rings?", "Which famous novel begins with the line “It was the best of times, it was the worst of times”?"]', '["Holden Caulfield", "F. Scott Fitzgerald", "Middle-earth", "A Tale of Two Cities"]', '[["Jay Gatsby", "Ernest Hemingway", "Harper Lee"], ["Narnia", "Westeros", "Hogwarts"], ["The Old Man and the Sea", "To Kill a Mockingbird", "The Hobbit"], ["Moby Dick", "Pride and Prejudice", "Dracula"]]'),
  ("kl3081", "Music Quiz", "Kate", '["Who is the lead singer of the band Coldplay?", "Which music artist has won the most Grammy Awards?", "What is the name of Adele’s debut album?", "What is the name of Michael Jackson’s third studio album?"]', '["Chris Martin", "Beyoncé", "19", "Off the Wall"]', '[["Adam Levine", "Chris Brown", "Justin Bieber"], ["Taylor Swift", "Alicia Keys", "Kanye West"], ["21", "25", "Hello"], ["Bad", "Thriller", "Dangerous"]]'),
  ("mn5327", "History Quiz", "Mike", '["What was the name of the first satellite launched into space?", "What year did the American Civil War end?", "Which country was the first to circumnavigate the globe?", "Who was the first female Prime Minister of the United Kingdom?"]', '["Sputnik 1", "1865", "Portugal", "Margaret Thatcher"]', '[["Vostok 1", "Explorer 1", "Soyuz 1"], ["1863", "1864", "1866"], ["Spain", "England", "France"], ["Indira Gandhi", "Angela Merkel", "Theresa May"]]'),
  ("dm7849", "Movie Quiz", "Dan", '["Who directed the movie Titanic?", "Who played the lead role in the movie Forrest Gump?", "What is the name of the hobbit played by Elijah Wood in The Lord of the Rings trilogy?", "What is the name of the main villain in The Lion King?"]', '["James Cameron", "Tom Hanks", "Frodo Baggins", "Scar"]', '[["Steven Spielberg", "Peter Jackson", "Christopher Nolan"], ["Robin Williams", "Matt Damon", "Leonardo DiCaprio"], ["Gollum", "Bilbo Baggins", "Gimli"], ["Jafar", "Ursula", "Maleficent"]]'),
  ("jp9375", "Art Quiz", "John", '["Who painted the Mona Lisa?", "Which artist is famous for his “drip” style of painting?", "Who painted the ceiling of the Sistine Chapel?", "Who created the sculpture David?"]', '["Leonardo da Vinci", "Jackson Pollock", "Michelangelo", "Donatello"]', '[["Pablo Picasso", "Claude Monet", "Vincent van Gogh"], ["Andy Warhol", "Salvador Dali", "Mark Rothko"], ["Raphael", "Titian", "Caravaggio"], ["Michelangelo", "Bernini", "Rodin"]]'),
  ("lb6890", "Science Quiz", "Lucy", '["What is the largest organ in the human body?", "What is the smallest planet in the solar system?", "What is the name of the process by which plants convert sunlight into energy?", "What is the only metal that is liquid at room temperature?"]', '["Skin", "Mercury", "Photosynthesis", "Mercury"]', '[["Brain", "Heart", "Liver"], ["Venus", "Mars", "Jupiter"], ["Respiration", "Transpiration", "Digestion"], ["Gallium", "Sodium", "Gold"]]'),
  ("pd2936", "Literature Quiz", "Peter", '["Who wrote the novel 1984?", "What is the name of the island in the novel Lord of the Flies?", "What is the name of the author of The Hobbit?", "What is the title of Jane Austen’s final completed novel?"]', '["George Orwell", "Piggy Island", "J.R.R. Tolkien", "Persuasion"]', '[["Aldous Huxley", "Ray Bradbury", "Margaret Atwood"], ["Gilligans Island", "Treasure Island", "Skull Island"], ["C.S. Lewis", "J.K. Rowling", "Stephenie Meyer"], ["Sense and Sensibility", "Northanger Abbey", "Mansfield Park"]]'),
  ("kb7831", "Sports Quiz", "Karen", '["What is the name of the stadium that hosts the Wimbledon tennis tournament?", "What is the name of the boxer who was known as “The Greatest”?", "Which city hosted the Summer Olympics in 2020?", "Which country is the current FIFA Women’s World Cup champion?"]', '["All England Lawn Tennis and Croquet Club", "Muhammad Ali", "Tokyo", "USA"]', '[["Centre Court", "Rod Laver Arena", "Arthur Ashe Stadium"], ["Joe Frazier", "Mike Tyson", "Floyd Mayweather Jr."], ["Rio de Janeiro", "Beijing", "Sydney"], ["Brazil", "Germany", "France"]]'),
  ("gm4928", "Geography Quiz", "Greg", '["What is the capital of South Africa?", "What is the smallest continent by land area?", "What is the largest ocean?", "What is the name of the largest desert in the world?"]', '["Pretoria", "Australia", "Pacific", "Sahara"]', '[["Johannesburg", "Cape Town", "Durban"], ["Asia", "Europe", "Antarctica"], ["Atlantic", "Indian", "Arctic"], ["Gobi", "Arabian", "Antarctic"]]'),
  ("cb1764", "Movie Quiz", "Carla", '["What is the highest-grossing animated movie of all time?", "Who played the character of Black Widow in the Marvel Cinematic Universe?", "Which movie won the Best Picture award at the 2021 Oscars?", "Who directed the movie The Shawshank Redemption?"]', '["Frozen II", "Scarlett Johansson", "Nomadland", "Frank Darabont"]', '[["The Lion King", "Toy Story 4", "Minions"], ["Gal Gadot", "Brie Larson", "Zoe Saldana"], ["The Trial of the Chicago 7", "The Father", "Mank"], ["Martin Scorsese", "Quentin Tarantino", "Christopher Nolan"]]');

  